name: primeira-pipeline

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Primeira ação
        run: echo "Hello world from pipeline !!"

      - name: Segunda ação
        run: |
          echo "Você criou a sua primeira pipeline workflow"
          echo "Parabéns!!"
