name: primeira-pipeline

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  primeiro-job:
     name: "Primeiro Job"
     runs-on: ubuntu-latest
     steps:
       - name: Primeira ação
         run: echo "Hello world from pipeline !!"

       - name: Segunda ação
         run: |
           echo "Você criou a sua primeira pipeline workflow"
           echo "Parabéns!!"
       - name: "Script Python"          
         run: |
           variavel = "Hi there"
           print(variavel)
         shell: python

  segundo-job:
    name: "Instalação ambiente Node.Js"
    runs-on: ubuntu-latest
    steps:
      - name: Verificação da versaõ do Node.Js
        run: node --version    
      - name: Definição da versão do Node.Js v20.13.1
        uses: actions/setup-node@v4
        with:
          node-version: '20.13.1'
      - name: Verificação da versão após instalção do Node.Js
        run: node --version 
